name: fullstack-auth-app

services:
    api:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        env_file: ./backend/.env
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - 3001:3001
