name: fullstack-auth-app

services:
    api:
        build:
            context: ./backend
            target: development
        restart: unless-stopped
        env_file: ./backend/.env
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - fullstack-auth-app

    frontend:
        build:
            context: ./frontend
            target: devlopment
            args:
                VITE_API_URL: https://api.auth.localhost
        restart: unless-stopped
        env_file: ./frontend/.env
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - fullstack-auth-app
        command: npm run dev -- --host
        depends_on:
            - api

    caddy:
        image: caddy:2-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - fullstack-auth-app
        depends_on:
            - api
            - frontend

volumes:
    caddy_data:
    caddy_config:

networks:
    fullstack-auth-app:
        driver: bridge
